1. Crear un arreglo con todos los numeros pares del 10 al 50

In [1]:
import numpy as np

In [7]:
numeros = np.arange(10,51,2)
numeros

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

2. Crear una matriz 3x3 con valores del 0 al 8

In [25]:
valores = np.arange(0,9)
valores.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Utilizar numpy para generar un arreglo de 25 numeros aleatorioas

In [17]:
numeros = np.random.random(25)
numeros

array([0.99443494, 0.75122097, 0.43475   , 0.65630112, 0.24701242,
       0.47404784, 0.59394129, 0.09424685, 0.67180628, 0.52626169,
       0.9678392 , 0.02794046, 0.14527668, 0.61146717, 0.46750911,
       0.41115309, 0.73373595, 0.33630494, 0.57776286, 0.27510305,
       0.48493885, 0.4484036 , 0.06889691, 0.67108522, 0.68363456])

4. Crea un arreglo de una dimension e imprime el valor de la suma de todos sus elementos

In [21]:
elementos = np.array([1,2,5,6,1])
np.sum(elementos)


15

5. Crea un arreglo de una dimension e imprime el valor de la media de todos sus elementos

In [24]:
elementos = np.array([1,2,5,6,1])
print(np.mean(elementos))
print(np.average(elementos))

3.0
3.0
